name: wasatch
channels:
- 'defaults'
dependencies:
- 'mkl=2017.0.1=0'
- 'numpy=1.11.3=py27_0'
- 'py=1.4.32=py27_0'
- 'python=2.7.13=0'
- 'six=1.10.0=py27_0'
- pip:
  - future==0.16.0
  - pygtail==0.7.0
  - pyusb==1.0.0
  - requests==2.13.0
