child.sendline(" get_secondary_adc_raw  ") 
child.expect(prompt)
child.sendline("	get_config_json	 ")
child.expect(prompt)
child.sendline(" connection_check  ") 
child.expect(prompt)
child.sendline(" set_tec_enable TRUE ") 
child.expect(prompt)
child.sendline(" set_detector_tec_setpoint_degc 15 ") 
child.expect(prompt)
child.sendline(" get_detector_temperature_degc  ") 
child.expect(prompt)
child.sendline(" connection_check  ") 
child.expect(prompt)
