#!/bin/bash
################################################################################
#                                  deploy                                      #
################################################################################
#                                                                              #
#  DESCRIPTION:  Quick script to consistently and reliably upload releases     #
#                to our website.                                               #
#                                                                              #
#  AUTHOR:       Mark Zieg <mzieg@wasatchphotonics.com>                        #
#                                                                              #
################################################################################

read -p "Username: " USERNAME

# render documentation 
make doc

# echo
# read -p "Press return to continue..." FOO

# upload documentation
rsync --archive doxygen/html/ ${USERNAME}@wasatchphotonics.com:www/api/Wasatch.PY/

echo
echo "View via:"
echo
echo "    http://www.wasatchphotonics.com/api/Wasatch.PY/"
